name: Build and push container
on:
  push:
    branches: 
      - main 
    paths:
      - .github/Dockerfile
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hipervincle/tofu-kube-hetzner
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=1.0.1
            type=raw,value=latest
            type=ref,event=tag
            type=sha,format=short
      - name: Build and push Docker image
        uses: docker/build-push-action@c0432d2e016ab17a336cee48256683e74d5c4c9e
        with:
          context: .
          file: .github/Dockerfile
          build-args: |
            GIT_USER_NAME=${{ vars.DEFAULT_GIT_USERNAME }}
            GIT_USER_EMAIL=${{ vars.DEFAULT_GIT_EMAIL }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
