name: Generate terraform docs
on:
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0 # Necessary to fetch all history for create-pull-request to work correctly

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c
      with:
        working-dir: .
        output-file: docs/terraform.md
        output-method: inject
        config-file: ".terraform-docs.yml"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Terraform documentation
        title: "[AUTO] Update Terraform Documentation"
        body: "Automated changes by GitHub Actions"
        branch: "docs/update-${{ github.head_ref }}"
        labels: documentation
