name: Lint

on:
  pull_request:

jobs:
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Scan terraform files with tfsec
    steps:
      - name: Clone repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@7a44c5dcde5dfab737363e391800629e27b6376b
        with:
          github_token: ${{ github.token }}
          tfsec_args: --ignore-hcl-errors

      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@a2f2edbf61c6bb22849de705d304b9d2af5f69cd
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: nofilter
          fail_on_error: true
          tfsec_flags: --ignore-hcl-errors

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: terraform validate
        uses: dflook/terraform-validate@03889814f1c6cf2fea714787218b2f4edc85c369

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@10eaa13fa61437aa51be2d12fafe95f152e3512d
