---
name: Publish a new Github Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b
        with:
          generateReleaseNotes: true
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
